apiVersion: v1
kind: ConfigMap
metadata:
  name: global-load-balancer
  namespace: default
  labels:
    app: realtime-voice

data:
  dns-config: |
    upstream:
      - region: us-east-1
        server: realtime-voice-us-east.example.com
      - region: eu-west-1
        server: realtime-voice-eu-west.example.com
